name: MSA integration test main
on:
 workflow_dispatch:
 push:
    branches:
      - main

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: RUNME.py
         git-branch: main
         databricks-host: https://adb-984752964297111.11.azuredatabricks.net
         databricks-token: ${{ secrets.DEPLOYMENT_TARGET_TOKEN_MSA }}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "Standard_DS3_v2",
             "azure_attributes": {
                            "availability": "ON_DEMAND_AZURE",
                            "first_on_demand": 1
                            }
           }
         notebook-params-json: >
           {
            "run_job": "True"
           }
